Leets-Makers/Weeth-FE

README.md
src/reportWebVitals.js

Docs/#2깃허브 문서 정리

---

.eslintignore
package-lock.json
package.json
src/App.js
src/components/BoardTitle.jsx
src/components/Button.jsx
src/components/CalendarHeader.jsx
src/components/Caption.jsx
src/components/EventDetail.jsx
src/components/Header.jsx
src/components/SmallButton.jsx
src/components/home/HomeFooter.jsx
src/components/home/HomeMiddle.css
src/components/home/HomeMiddle.jsx
src/index.css
src/pages/Calendar.css
src/pages/EventDetail.jsx
src/pages/Home.jsx
src/styles/theme.js

##설명
- 전체적인 home ui 구성
- 근데 마진이 좀 이상해서,, 많은 수정 필요,,,

Feat/#5/home UI 구현

---

src/components/BoardTitle.jsx
src/components/Calendar/CalendarHeader.jsx
src/components/home/HomeMiddle.jsx
src/pages/Calendar.jsx

[hotfix] 경로 오류 수정

---

src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/ToggleButton.jsx
src/pages/Calendar.css
src/pages/Calendar.jsx
src/pages/EventDetail.jsx

/calender, /event에 대해 width를 370px로 수정

Style/#18/페이지 너비 변경

---

src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/ToggleButton.jsx
src/components/Calendar/YearCalendar.jsx
src/pages/Calendar.css
src/pages/Calendar.jsx

- 캘린더 페이지에서 월/년 단위를 선택할 수 있는 토글 생성
- 토글 창 어느 곳을 클릭하든 토글 버튼이 이동합니다
- 선택된 것은 하얀색, 선택되지 않은 것은 옅은 회색의 글씨로 나타납니다
- 현재 토글창이 값을 관리하는 부분은 구현이 되지 않아 아래쪽에 month/year버튼을 그대로 두었습니다
- 노트북이 계속 이상했는데 화면 픽셀 깨짐 / 입력 불가 상태가 지속적으로 나타나는 관계로 조금 더딥니다 .... 내일(7/19)  아침 바로 서비스센터 방문 예정이며 최대한 빠르게 개발 진행하겠습니다............... ㅠㅠ

#8 feat: month/year 토글 생성

---

src/App.js
src/components/Signup/SignupMemInput.jsx
src/components/Signup/SignupTextComponent.jsx
src/components/Signup/SignupWhite.jsx
src/pages/Profile.jsx
src/pages/Signup.jsx

오류 수정 및 진행상황 merge
- 오류 수정 및 추가 오류 방지를 위해 작업 중이던 branch merge
🛠 작업 중이던 내용
- 회원가입 이메일 input
- 회원가입 후 개인정보 입력 UI 구현
아직 회원가입 페이지가 완성된 것은 아니라 추가 수정 있을 예정입니다.

#36 fix: 오류 수정 및 진행상황 merge

---

src/components/MyPage/InfoInput.jsx
src/components/MyPage/MyPageHeader.jsx
src/pages/Edit.jsx
src/pages/MyPage.jsx

마이페이지 수정
- 수정 페이지 간격 수정
- 수정란 폰트 사이즈 수정
- 탈퇴하기 추가 -> 클릭 시 '탈퇴하시겠습니까?'
- 뒤로가기 기능 추가
/mypage, /edit 페이지 또한 **디자이너 컨펌 전** 추가 수정사항 없습니다

#43 feat: 마이페이지 수정

---

src/components/Member/Category.jsx
src/pages/Member.jsx

- 기수별 멤버 조회 기능 추가
- 기수 선택시 해당 기수인 멤버들만 렌더링 되도록 함
- default 선택값을 전체로 설정
생각보다 많이 복잡하진 않았네요 머쓱ㅎㅎ,,,,

#24 feat: 기수별 멤버 조회 기능 추가

---

src/components/Attendance/Modal/ModalAttend.css
src/components/Attendance/Modal/ModalAttend.jsx
src/components/Attendance/Modal/ModalPenalty.jsx

ModalAttend.css와 CalendarHeader.jsx의 스타일 컴포넌트의 설정 충돌로 캘린더 페이지의 모달이 나오지 않는 문제를 해결했다.
모달알못이라 전에 미션 할 때 했던 모달 css를 그냥 가져다 써서 생긴 문제였다..
전체 모달에 적용되는 css 설정을 없애고 아래처럼 스타일 컴포넌트로 만들어서 내 모달에만 적용해 줬다
예진 암 쏘리,,

#49 Fix: 모달 css 충돌 오류 해결

---

src/components/Signup/RoleSector.jsx
src/components/Signup/SignupHeader.jsx
src/components/Signup/SignupMemInput.jsx
src/components/Signup/SignupTextComponent.jsx
src/components/Signup/SignupWhite.jsx
src/components/home/HomeMain.jsx
src/pages/Profile.jsx
src/pages/Signup.jsx

프로필 페이지 UI 마무리 및 기능 구현
- 조건을 충족시켰을 때 페이지를 이동하게 하는 기능은 추후 구현 예정

#98 design: 회원가입 정보 입력 프로필 페이지  UI 구현(기능까지)

---

public/index.html
src/hooks/UserAPI.jsx

[hotfix] 메타태그 누락 수정

---

.eslintignore
src/App.js
src/components/BoardTitle.jsx
src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/YearCalendar.jsx
src/hooks/EventAPI.jsx
src/hooks/EventContext.js
src/pages/Calendar.jsx
src/pages/Edit.jsx
src/pages/EventDetails.jsx
src/pages/MyPage.jsx

캘린더 api 연결
- 일정 상세 조회
- 기간 일정 조회 (달)
- 년도별 일정 조회 (년)
에러처리를 까먹어서 ... user api 연결 끝내고 일괄로 하겠습니당

#112 feat: 캘린더 api 연결

---

src/components/Attendance/AttendMain.jsx
src/components/Attendance/Modal/ModalAttend.jsx
src/components/Button/Button.jsx
src/hooks/AttendContext.js
src/hooks/PenaltyContext.js
src/pages/Attendance.jsx
src/pages/Login.jsx

#121 feat: 출석체크 api 연결

---

.eslintignore
src/components/DropdownMenu.jsx
src/components/Header/LeftButton.jsx
src/components/MyPage/InfoInput.jsx
src/components/MyPage/MyPageHeader.jsx
src/hooks/UserContext.js
src/pages/Edit.jsx
src/pages/MyPage.jsx
src/styles/theme.js

유저 관련 api 연결
✔️ 탈퇴 api 연결
✔️ 내 정보 수정
- api 연결
- 비밀번호 변경 추가 (눈표시)
- 학과 입력 드롭다운으로 수정
- 역할(포지션) 수정 못하도록
✔️ 탈퇴하기 / 수정 완료 버튼 클릭 시 confirm 뜨게
-> 클릭반경 문제였나봄.. 클릭반경 늘리니까 됨... 나중에 다른 것도 수정해야겟음.
예외처리는 어드민 하고나서...........,,,,

#119 feat: 유저 api 연결

---

src/components/Dues/DueCategory.jsx
src/components/Dues/DuesInfo.jsx
src/components/Receipt/ReceiptMain.jsx
src/hooks/DuesContext.js
src/pages/Dues.jsx

#132 fix: 회비 수입 수정

---

src/components/Attendance/AttendMain.jsx
src/components/Button/Button.jsx
src/pages/Dues.jsx
src/pages/Landing.jsx

#136 fix: 자잘한 오류 수정 및 회비 페이지 total 돈 제거

---

src/App.js
src/assets/images/ic_plus.svg
src/components/BoardTitle.jsx
src/components/Calendar/CalendarHeader.jsx
src/components/Calendar/DateInput.jsx
src/components/Calendar/ModalMonthContent.jsx
src/components/EditDelModal.jsx
src/components/Header/Header.jsx
src/components/MyPage/InfoInput.jsx
src/pages/CreateEvent.jsx
src/pages/Edit.jsx
src/pages/EditEvent.jsx
src/pages/EventDetails.jsx
src/pages/Login.jsx

어드민 api 연결
- 어드민 여부에 따라 페이지 이동 버튼 조건부 렌더링
- 일정 생성 api 연결 - 생성 페이지 새로 만듦
- 일정 삭제 api 연결
- 일정 수정 페이지는 만들었고, api 연결은 안됨
- 모달 구현
props로 제목(메뉴는 고정이고 앞에 '일정'부분을 수정할 수 잇음), 수정/삭제/취소하기에 대한 온클릭 함수를 받음
- 모달을 만들긴 햇는데 이게 모달 콘텐츠만 만든거라... 위치 설정은 모달을 만든 페이지에서 해줘야됨! -> 하다가 css가 잘 안먹어서 일단 냅두고 다른거 햇읍니다..
- 아 그리고 이게.. 일정 세부 페이지가 /event/{eventId}로 연결된 게 아니엇더라구요...........ㅜ-ㅜ 아마 EventAPI를 없애고 (필요한 페이지로 옮기고) EventDetailAPI, EventDetaiContext로 수정해야할 것 같아서 만들어만 둿어요 연결은 안됨 ㅠㅠ

#128 feat: 어드민 api 연결

---

src/assets/images/ic_logout_gray.svg
src/assets/images/ic_logout_white.svg
src/pages/MyPage.jsx

#139 feat: 탈퇴하기 버튼으로 수정 및 로그아웃 버튼 추가

---

src/components/SignupDropDown.jsx
src/pages/Profile.jsx
src/pages/Signup.jsx

회원가입 api 및 이메일 중복 api 연결
- 영어만 입력 가능
- 중복 검사 안 하면 다음으로 못 넘어감
- 이메일 입력칸 비워지면 다시 검사 가능
- 예진이가 만든 드롭다운메뉴 가져다가 회원가입 드롭다운 디자인으로 변경
- 빈칸 있으면 완료 버튼 안 눌림
폰번호랑 학번 중복 검사는 아직 구현 안 됨,,

#135 feat: 회원가입 api 연결

---

src/components/home/HomeMain.css
src/hooks/Utils.js
src/pages/Home.jsx
src/pages/Login.jsx

#151 fix: 로그인 api 연결시 로컬에 토큰 저장

---

src/components/Calendar/DateInput.jsx
src/components/Calendar/ModalMonthContent.jsx
src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/YearCalendar.jsx
src/components/Member/MemberName.jsx
src/components/MyPage/InfoInput.jsx
src/hooks/EventAPI.jsx
src/hooks/EventContext.js
src/pages/Calendar.jsx
src/pages/Login.jsx

기능상의 오류 수정
- 캘린더 모달 입력 안 되는거 수정
컴포넌트화 하면서 변수명 바뀐거 반영 안해서 그런거였음..
- 년을 바꿔도 반영이 안되는 문제 수정 -> 지금은 2023년으로 넘어가면 다른 일정이 뜹니다 후...
- 기수가 여러개인 경우 최초의 기수만 보이도록 수정 (admin 계정은 1,2,3기입니다)
토큰은 새 이슈 파서 하는걸로..
입력제한을 아직 못 했는데 오늘 안에 끝내도록 하겠습니다 ㅠ-ㅠ

#145 feat: 캘린더 모달 수정

---

src/components/Calendar/MonthlyEvent.jsx
src/pages/CreateEvent.jsx
src/pages/EditEvent.jsx

저번 pr에 커밋이 하나 누락됐나바여. 수정완!
이제 일정 생성/수정 가능합니다

#159 hotfix: 어드민 생성 수정 오류 고침

---

src/components/DropdownMenu.jsx
src/components/MyPage/InfoInput.jsx
src/pages/Edit.jsx
src/pages/MyPage.jsx

#169 hotfix: 수정페이지 원상복구

---

.eslintignore
src/components/Board/AttachButton.jsx
src/components/Board/FileAttachMenu.jsx
src/pages/BoardDetail.jsx
src/pages/BoardPosting.jsx

- 글쓰기 페이지에서 엑스 버튼 누르면 사진 삭제되도록 하기
큰 변경 사항 없이  develop pull 한 상태입니다..

#170 fix: 글쓰기 페이지 X버튼 클릭 시 사진 삭제 기능 구현

---

src/App.js
src/components/Attendance/AttendCheckMain.jsx
src/components/Attendance/AttendMain.jsx
src/components/Attendance/Modal/ModalAttend.jsx
src/components/Attendance/Modal/ModalPenalty.jsx
src/hooks/AttendAPI.jsx
src/hooks/AttendCheckAPI.jsx
src/hooks/AttendContext.js
src/hooks/PenaltyAPI.jsx
src/hooks/PenaltyContext.js
src/pages/AttendCheck.jsx
src/pages/Login.jsx
src/router/PrivateRouter.jsx

- url로 직접적인 접근 제한
-> home은 일단 풀어 놧어요,, 자동 로그인 기능 만들면 home도 추가하겟습니다 ㅎ..
- 패널티 응답 데이터 구조 변경에 따른 data 응답 수정
- 출석 페이지 null data 응답 로직 추가
- 출석 조회 페이지 null data 응답 로직 추가 
출석 조회에 attendances는 바뀐 거 없는지 물어보기,, 
출석 메인 페이지 조회 api는 startDateTime가 start로 바뀌엇는데 킹리적 갓심으로 저것도 바꼈을 것 같다.. 
일단 자고 앞으로는 기필코 밤낮을 바꿀 것이다... 😿

#179 fix: 출석 에러 수정

---

src/App.js
src/components/Attendance/AttendCheckMain.jsx
src/components/Attendance/AttendMain.jsx
src/components/Attendance/Modal/ModalAttend.jsx
src/components/Dues/DuesInfo.jsx
src/hooks/AttendAPI.jsx
src/pages/Dues.jsx
src/router/PrivateRouter.jsx

- 출석체크 api 명세대로 수정
- 출석 시간이 지날 경우 출석 버튼 비활성화 됨
- 회비 데이터 받아올 때 null 일 경우 로직 추가

#183 fix: 출석 체크 api 수정

---

public/index.html
src/App.js
src/components/BoardTitle.jsx
src/components/EditDelModal.jsx
src/pages/EventDetails.jsx
src/pages/Member.jsx
src/router/ScrollToTop.jsx

피드백 및 수정사항 일부 반영
수정사항 n번은 팀방에 올라온 pdf 기준!!
- 시계/배터리 상단바 부분까지 배경색 올라오도록 설정
-> index.html에서 theme 수정하여 설정
- 헤더 상단마진 제거
-> 해당 pr 머지 후 확인하는 편이 나을 것 같아서 일단 수정 없이 pr올립니당,,
- 수정사항 1번
-> 장기일정인 경우 시계 아이콘을 없앰~!
- 페이지 이동 시 스크롤 리셋
-> `ScrollToTop` 컴포넌트를 이용하여 설정 완. 수정사항 2번도 해결이 되는지는 배포 후 확인해야할듯.
- 수정사항 5번
-> height를 `100vh`로 수정함

#191 fix: 피드백 및 수정사항

---

.eslintignore
src/components/Attendance/AttendCheckMain.jsx
src/components/Attendance/AttendMain.css
src/components/Attendance/AttendMain.jsx
src/components/Signup/SignupHeader.jsx
src/components/Signup/SignupMemInput.jsx
src/hooks/PenaltyAPI.jsx
src/hooks/PenaltyContext.js
src/pages/Dues.jsx
src/pages/Login.jsx
src/pages/Profile.jsx
src/pages/Signup.jsx

패널티 에러만 수정했어야 했는데.. 모든 에러를 여기서 수정했읍니다..
_**충석**
- 유저이름 상하 간격 조정
_**패널티**_
- 패널티 유무에 따라 보이는 컴포넌트 로직 수정
- 패널티 null일 경우의 에러 로직 추가
_**회비**_
- 총 금액에 '원' 추가
_**회원가입**_
- 이메일 비번 한번에 뜨도록 수정
- 기수 1~4 사이 한자리 숫자만 입력 가능하게 수정
- 비밀번호 특수문자 입력 제한
_**로그인**_
-이메일 비번 입력 안 됐을 때 완료 버튼 못 누르게 수정(alert 창 뜸)

#197 fix: 패널티 에러 수정

---

src/components/Calendar/CalendarHeader.jsx
src/components/Calendar/DateInput.jsx
src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/YearCalendar.jsx
src/components/Header/Header.jsx
src/components/Member/Category.jsx
src/components/MyPage/MyPageHeader.jsx
src/index.css
src/pages/Member.jsx

이것저것 수정햇습니다,,,
- 문제점,,, 2월 30,31일 4월 31일 등 31일까지는 유효하지 않은 날짜임에도 입력이 가능합니다... 임원을 믿기? 어떰? 막이래
- 완전히 제거할 시 pc에서 보기 불편해짐 -> 기존에 45px이엇던 것을 25px로 수정!
- 월화수목금토일 - 여기 테두리 재설정
- 마진 수정하면서 모달 위치도 변경
- 기수 내림차순으로 변경
- 년도별 일정 상반기/하반기로 나눔
제 생각에 이정도면 잘 굴러가는 것 같습니다.. 물론 보완해야할 점이 분명히 잇지만서도.....,,,

#200 fix: 날짜 입력 제한 수정

---

src/components/Board/BoardComment.jsx
src/components/Board/CommentList.jsx
src/components/Board/FileAttachMenu.jsx
src/components/Board/NoticeHeader.jsx
src/components/Board/NoticeList.jsx
src/pages/NoticeDetail.jsx
src/pages/StudyDetail.jsx

-QA에서의 수정사항 수정
- 첨부파일 첨부/완료 버튼
- 게시판 작성자만 …버튼 보이게 수정
- 게시판 첨부파일 있을 때만 렌더링되게 수정
- 댓글-대댓글 문제 해결
- 헤더 마진 조절
해야할 일 : 
- 더 불러오기 버튼 대체
- 입력창 조절(위치고정/typing)
- 댓글/대댓글 정리 - 마지막으로 안되는 거 있나 확인하기
- 글쓰기할 때 확대되는 ios믄제 해결법

Feat#203/입력창 고정하기 게시글 더 불러오기 버튼 수정

---

src/components/Attendance/AttendHeader.jsx
src/components/Dues/DuesHeader.jsx
src/components/Login/LoginHeader.jsx
src/components/Signup/SignupHeader.jsx

release 배포 확인용으로 헤더 마진 고친거라 이슈로 파지 않앗습니다,,
다음 것 부터는 이슈 파서 할게욤 🥹

fix: 헤더 마진 25px로 수정

---

src/components/Attendance/AttendCheckMain.jsx
src/components/Attendance/AttendMain.jsx
src/components/Receipt/ReceiptInfo.jsx
src/components/home/HomeMain.jsx
src/hooks/UserAPI.jsx
src/pages/Login.jsx

- 홈에 이름 error로 뜨는 거 수정
-> userData를 받아올 때도 error로 뜨길래, 기존 로직 수정해서 error일 경우 없앰
- 출석 상태 미결-출석-결석으로 수정
- 영수증 지출 이름을 이월금액에서 지출 설명으로 바꿈

#206 fix: 출석 상태 변경

---

src/components/Board/BoardComment.jsx
src/components/Board/CommentList.jsx

- 댓글/대댓글 기능 수정 사항 마무리하기
- 댓글 작성자만 삭제 기능
- 댓글 삭제 시, 해당 댓글의 대댓글 기능 구현 막기
- 댓글 삭제 시, 작성자 이름 '알 수 없음' 으로 변경

#208 feat: 댓글 대댓글 기능 수정마무리

---

src/components/Board/NoticeList.jsx
src/components/Board/StudyList.jsx
src/pages/Home.jsx

최종 수정사항들 수정하기
최신 게시물 15개까지 볼 수 있게 수정하기
-> 마지막 게시물까지 다다르면 '더 보기' 버튼이 보이지 않도록 수정하기

#214 fix: 최종 수정사항 정리하기

---

src/App.js
src/components/Board/AttachButton.jsx
src/components/Board/BoardComment.jsx
src/components/Board/CommentList.jsx
src/components/Board/Typing.jsx
src/components/Button/MiddleButton.jsx
src/components/Button/SmallButton.jsx
src/components/Caption.jsx
src/components/Receipt/ReceiptMain.jsx
src/components/home/HomeMain.jsx
src/hooks/MonthlyScheduleAPI.jsx
src/hooks/YearlyScheduleAPI.jsx
src/pages/Landing.jsx
src/pages/NoticeDetail.jsx
src/pages/NoticePosting.jsx
src/pages/Signup.jsx
src/pages/StudyDetail.jsx
src/pages/StudyPosting.jsx

커밋 메세지 feat 해야 됏는데 fix로 했네.. 큰 문제는 아니니까 걍 두겟습니다 ㅋㅅㅋ
- 랜딩 페이지에서 로컬 스토리지 토큰 유무 확인 후 토큰 있으면 바로 홈으로 리다이렉션
- 영수증 페이지 3,8월/ 9,2월까지 나눠서 뜨도록 설정(현재 날짜와 비교해서 맞는 기간으로 보여줌)
- 홈에 기수 UserAPI에서 받아오는 기수로 보이도록 수정

#219 feat: 자동 로그인 추가

---

.eslintignore
src/components/BoardTitle.jsx
src/components/Calendar/CalendarHeader.jsx
src/components/Calendar/DateInput.jsx
src/components/Calendar/ModalMonthContent.jsx
src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/ToggleButton.jsx
src/components/Calendar/YearCalendar.jsx
src/components/Member/Category.jsx
src/components/Member/MemberHeader.jsx
src/components/Member/MemberName.jsx
src/hooks/MonthlyScheduleAPI.jsx
src/hooks/YearlyScheduleAPI.jsx
src/pages/Calendar.jsx
src/pages/Member.jsx

QA 수정했습니다..~
- 캘린더(년) 모달에서 년도 수정 시 에러가 뜨던 것을 수정했습니다..~
- 못생긴 에러들을 조금 보기 좋게? 수정했습니당..~
- 멤버 에러의 경우 데이터가 존재하지만 불러오지 못한 경우와 데이터가 아예 존재하지 않는 경우로 나뉘기 때문에 에러도 그에 맞게 나누었습니다
- 멤버 배경을 멤버수에 맞게 렌더링 되도록 수정했습니다~~~이제 멤버가 많아져도 배경이 잘리지 않아요,,,
이제 제발 캘린더 멤버에서는 수정 사항이 없길..

#215 fix: QA 수정

---

src/components/Board/BoardComponent.jsx
src/components/Board/CommentList.jsx
src/components/Board/NoticeList.jsx
src/components/Board/StudyList.jsx
src/components/Board/Typing.jsx
src/pages/NoticeDetail.jsx
src/pages/StudyDetail.jsx

- 게시판 추가 수정사항 해결
- 새로고침시, 페이지 오류나는 문제 해결
- 제목, 게시글 줄바꿈
- StudyList, NoticeList에서 Utils 제거하기
- 게시글/공지사항 미리보기에서 일정 글자 수 이상 늘어날 시, ...으로 보이도록 수정
- 원래는 로그인 QA도 해결하고 싶었는데... 못 했습니다ㅠㅠ

#221 fix: 게시판 수정 사항 수정하기

---

src/components/Board/AttachButton.jsx
src/components/Board/BoardComponent.jsx
src/pages/NoticeDetail.jsx
src/pages/NoticePosting.jsx
src/pages/StudyDetail.jsx
src/pages/StudyPosting.jsx

- 게시판 컴포넌트 레귤러 적용
- 게시물 생성 전 alert로 경고창 보내기
- 파일 업로드 시, 하나의 파일만 받을 수 있는 문제 해결하기
- 게시판 컴포넌트 레귤러 적용
- 게시물 생성 전 alert로 경고창 보내기
- 파일 업로드 시, 하나의 파일만 받을 수 있는 문제 해결하기

#227 fix: 최종 수정사항 수정하기

---

src/components/Board/AttachButton.jsx
src/components/Board/FileAttachMenu.jsx
src/pages/NoticeDetail.jsx
src/pages/NoticePosting.jsx
src/pages/StudyDetail.jsx
src/pages/StudyPosting.jsx

1. 첨부 버튼 최대 두 개까지 나타날 수 있도록 수정
2. 첨부 버튼 한 개당 하나의 링크로 볼 수 있도록 함
3. 게시물 생성/수정 전에 '생성/수정 하시겠습니까?' 창 뜨게 하기

#230 fix: 게시물 첨부 버튼 수정하기

---

src/components/Signup/SignupTextComponent.jsx
src/pages/Login.jsx
src/pages/Profile.jsx
src/pages/Signup.jsx

- 로그인, 회원가입 엔터로 다음 페이지 넘어가기
- 회원가입 프로필 입력시 학번, 휴대폰 번호 유효한 입력 설정 추가

#231 fix: 엔터로 페이지 넘어가기

---

src/hooks/DuesAPI.jsx

hotfix: 회비 api 기수 수정

---

package-lock.json
src/components/Receipt/ReceiptMain.jsx

영수증을 이미지 파일이 아닌 pdf으로 올리는 상황 발생
기존 img 태그를 embed 태그로 변경하여 해결
-  but,, embed 태그가 클릭이 되지 않아 모달창이 열리지 않는 새로운 이슈 발생,,,
-> 위에 투명한 버튼 올리는 것으로 클릭 이슈 해결!
스크롤이 사라지지 않고 모양이 조금.. 이상함.. 일단 나중에 고치는 것으로 결정

hotfix: 영수증 pdf 파일도 보이도록 수정

---

src/api/deleteUser.tsx
src/components/Event/EventEditor.tsx
src/components/MyPage/MyInfo.tsx
src/pages/MemberDetail.tsx
src/pages/MyPage.tsx
src/styles/mypage/Mypage.styled.ts

#257 을 구현했습니다
<br>
수정페이지도 같이 리팩토링 하려 했는데...
과거의 제가 왜 코드를 이렇게 썻는지 이해가 안됩니다....ㅠ
시간이 너무 오래 걸릴 것 같아 마이페이지만 pr 올립니다..
<br>
<br>
- 탈퇴 api 분리
- 마이페이지 내 컴포넌트가 객체를 매핑하도록 리팩토링
<br>
<br>

#257 refactor: 마이페이지 리팩토링

---

src/api/BoardAPI.tsx
src/components/Board/Comment.tsx
src/components/Board/Info.tsx
src/components/Board/PostDetailMain.tsx
src/components/Board/PostFile.tsx
src/components/Board/PostListItem.tsx
src/components/Board/ReplyComment.tsx
src/styles/board/Comment.styled.ts
src/styles/board/PostDetail.styled.ts
src/styles/board/PostFile.styled.ts
src/styles/board/PostListItem.styled.ts
src/styles/theme.ts

게시판 목록, 게시판 상세 페이지의 컴포넌트 스타일을 분리 했습니다.
#c1c1c1의 그레이 스케일 값이 없어서 lightGray 를  추가했습니다.
게시판 api 및 다른 api 구조는 다음 이슈에서 고칠 예정이기 때문에 현재 게시판에 들어가도 목록이 뜨지 않습니다!

#287 Design: 게시판 스타일 분리

---

src/assets/images/ic_BE_clip.svg
src/assets/images/ic_DE_clip.svg
src/assets/images/ic_FE_clip.svg
src/components/MyPage/MyInfo.tsx
src/components/common/CardinalTag.tsx
src/pages/MemberDetail.tsx

#392 를 구현했습니다
<br>
<br>
<br>
변경된 멤버페이지 디자인을 반영하고, 기수태그 색상을 props에 따라 설정할 수 있도록 수정했습니다
<br>
<br>

#392 feat: 멤버 디자인 수정

---

package-lock.json
package.json
src/api/useGetMonthSchedule.tsx
src/components/Board/Comment.tsx
src/components/Board/ReplyComment.tsx
src/components/Calendar/MonthCalendar.tsx
src/components/Calendar/ScheduleItem.tsx
src/components/Event/EventContent.tsx
src/components/Event/EventEditor.tsx
src/components/Event/EventTitle.tsx
src/components/Modal/DeleteModal.tsx
src/components/home/HomeMain.tsx
src/hooks/useCustomBack.tsx
src/pages/BoardPostDetail.tsx
src/pages/Calendar.tsx
src/pages/Edit.tsx
src/pages/EventDetail.tsx
src/pages/MyPage.tsx
src/pages/NoticePostDetail.tsx
src/styles/calendar/MonthCalendar.styled.ts

#393 을 구현했습니다
<br>
<br>
https://github.com/user-attachments/assets/b21b05a3-68d8-4e53-ab65-e722a469b7dc
<br>
현재 디자인이 나오지 않아서 우선 오늘 표시와 구분만 되도록 설정해두었습니다.
상세조회에서 뒤로가기를 해도 이전에 보고있던 달이 그대로 보입니다!
- `DeleteModal`을 `SelectModal`로 변경했습니다. type이라는 props값을 추가로 받으며, 값을 전달하지 않을 시 기본은 negative(빨강)입니다
<br>
<br>

#393 feat: 일정 리스트 수정

---

package-lock.json
package.json
src/api/useGetAllUsers.tsx
src/api/useGetMonthSchedule.tsx
src/api/useGetUserInfo.tsx
src/api/useGetYearlySchedule.tsx
src/components/Calendar/MonthCalendar.tsx
src/components/Calendar/ScheduleItem.tsx
src/components/Calendar/YearCalendar.tsx
src/components/Event/EventEditor.tsx
src/components/Event/PickerModal.tsx
src/components/Member/MemberList.tsx
src/components/MyPage/MyInfo.tsx
src/components/common/CardinalDropdown.tsx
src/components/home/HomeInfo.tsx
src/pages/Edit.tsx
src/pages/Home.tsx
src/pages/Member.tsx
src/pages/MemberDetail.tsx
src/styles/calendar/MonthCalendar.styled.ts
src/styles/event/DatePicker.css
src/styles/mypage/Mypage.styled.ts

#401 을 구현했습니다
<br>
로딩 시간이 애니메이션 시간보다 짧을 경우, 애니메이션이 배속되면서 로딩이 없는 것보다 더 보기 불편한 상황이 생깁니다,,
강제로 지연시간을 추가하는 방법도 있겠지만, 이렇게 할 경우 불필요한 로딩이 계속 나타나는거라... 최적화 등의 방법으로 다시 해결해야할 것 같습니다ㅠㅠ
<br>
https://github.com/user-attachments/assets/34f6b208-cd7c-4a7d-8f29-c4ffaf291a3c
https://github.com/user-attachments/assets/ca7e8b2f-efab-4478-ade1-e645da8ab403
<br>
- 일정이 없는 경우 디자인 추가, 일정 컴포넌트 사이즈 및 정렬 수정
- 모바일에서 날짜가 선택되지 않는 에러 해결
- 일정이 4개 이상일 경우 달력엔 3개까지만 나타나도록 함
- 기수 드롭다운 수정
- 로딩 컴포넌트 적용
<br>
DatePicker 기본 css에 import 문제가 계속 발생하여 스타일을 직접 지정해주었습니다!
<br>

#401 feat: 로딩 컴포넌트 적용 및 디자인 수정

---

src/App.jsx
src/api/editBoard.tsx
src/api/editNotice.tsx
src/api/postBoard.tsx
src/api/useGetBoardDetail.tsx
src/pages/BoardEdit.tsx
src/pages/BoardNoticeEdit.tsx
src/pages/BoardNoticePost.tsx
src/pages/BoardPostDetail.tsx
src/styles/board/BoardPost.styled.ts
tsconfig.json

#402 를 구현했습니다
<br>
<br>
https://github.com/user-attachments/assets/b40c0387-0e95-4c2a-acc2-d95a15186f41
<br>
게시글 / 공지사항 수정 시 기존에 있던 파일을 포함하여 수정이 가능하도록 구현했습니다.
기존 파일과 새로 추가되는 파일을 따로 관리하여 api 요청 시 하나의 객체로 전달하도록 했습니다~!
우선은 돌아가게 구현하기 위해,, 다시 파일을 분리했는데, 리팩토링하여 한번에 관리할 수 있도록 수정해보겠습니다(〃･ิ‿･ิ)ゞ
<br>
<br>

#402 feat: 파일 수정 구현

---

src/App.jsx
src/api/deletePost.tsx
src/api/postBoard.tsx
src/api/postComment.tsx
src/api/useGetBoardDetail.tsx
src/pages/Board.tsx
src/pages/BoardDetail.tsx
src/pages/NoticeDetail.tsx

#407 을 구현했습니다
<br>
<br>
<br>
- api 엔드포인트 posts -> board 수정
- UI컴포넌트명 `BoardPostDetail` -> `BoardDetail`, `NoticePostDetail` -> `NoticeDetail`로 변경 (불필요한 단어 삭제)
- #405 에서 언급되었던 부분 반영하여 수정했습니다
- `NoticeDetail`에 하이라이팅 관련 코드가 반영되어있지 않아 추가했습니다. 동일한 UI에 파일을 분리한 경우, 꼼꼼하게 확인하면 좋을 것 같아요!
<br>
<br>

#407 feat: api 수정사항 반영

---

src/api/deleteComment.tsx
src/api/deletePost.tsx
src/api/patchAttend.tsx
src/api/postComment.tsx
src/api/useGetBoardDetail.tsx
src/api/useGetBoardInfo.tsx
src/api/useGetDuesInfo.tsx
src/api/useGetPenalty.tsx
src/assets/images/ic_default_position.svg
src/components/Attendance/AttendCheckMain.tsx
src/components/Attendance/AttendMain.tsx
src/components/Attendance/Modal/ModalAttend.tsx
src/components/Board/Comment.tsx
src/components/Board/CommentInput.tsx
src/components/Board/SlideNotice.tsx
src/components/Receipt/ReceiptMain.tsx
src/components/home/HomeInfo.tsx
src/components/home/HomeNotice.tsx
src/pages/Board.tsx
src/pages/BoardDetail.tsx
src/pages/Dues.tsx
src/pages/Home.tsx
src/pages/Notice.tsx
src/pages/NoticeDetail.tsx
src/styles/board/Comment.styled.ts
src/styles/home/HomeInfo.styled.ts

로딩 컴포넌트 및 api 인스턴스를 적용했습니다!
게시판에 로딩을 적용하려니까 구조부터 좀 바꿀 필요를 느껴서,,,, 일단 다음 이슈 파서 게시판 코드 리팩토링 하면서 로딩 적용을 해보겠습니다,,, 
<br>
- 게시판 제외 홈, 출석, 회비, 영수증 페이지 로딩 컴포넌트 적용 했습니다.
- api 인스턴스 적용 했습니다!
홈 공지사항도 좀 더 자연스럽게 바꾸려 했는데 잘 안 돼서,, 좀 더 찾아보고 바꿔볼게요!

#396 Fix: api와 로딩 적용

---

package-lock.json
src/api/admin/dues/adminReceipts.ts
src/components/Admin/Cardinal.tsx
src/components/Admin/DuesRegister.tsx
src/components/Admin/DuesRegisterAdd.tsx
src/pages/admin/AdminDues.tsx
src/styles/admin/DuesRegisterAdd.styled.ts
src/styles/admin/DuesRegisterDropDown.styled.ts
src/styles/admin/TotalDues.styled.ts

#404 를 구현하였습니다
<br>
<br>
<br>
2차 qa 수정
- 회비 메시지 오류 예외처리
- 회비 네비바 크기 조정 수정 완료
- 기수 드롭다운 순서 정렬
<br>
<br>

#404 Fix: 2차 qa 수정

---

src/api/admin/cardinal/postCardinal.ts
src/api/admin/member/deleteUser.ts
src/api/admin/member/getAdminUser.ts
src/api/admin/member/patchUserManagement.ts
src/api/admin/penalty/getPenalty.ts
src/api/admin/penalty/modifyPenalty.ts
src/components/Admin/MemberListTableHeader.tsx
src/components/Admin/Modal/CardinalEditModal.tsx
src/components/Admin/Modal/CommonModal.tsx
src/components/Admin/Modal/MemberDetailModal.tsx
src/components/Admin/PenaltyAdd.tsx
src/components/Admin/PenaltyDetail.tsx
src/components/Admin/PenaltyListTable.tsx
src/components/Admin/PenaltySubHeaderRow.tsx
src/components/Admin/SelectedTopBar.tsx
src/components/Admin/context/MemberContext.tsx
src/components/Admin/context/PenaltyReducer.ts
src/pages/admin/AdminPenalty.tsx
src/styles/admin/penalty/Penalty.styled.ts

추가 qa 내용들을 수정했습니다
<br>
<br>
<br>
1. 기수 변경 - 직접 입력으로 기존 기수도 입력 가능 && 임시 기수는 기존 기수 중 최대값보다 +1 기수만 입력되도록 수정 
2. 패널티 페이지 - 패널티 부여 후 새로고침하지 않고 바로 반영되도록 수정 && 이 상태에서 해당 패널티를 수정/삭제하려고 하면 패널티 id 값이 제대로 .. 전달되지 않아서인지 에러가 났는데 이것도 해결했습니다..! 
3. 가입승인된 멤버일 시 가입승인 버튼 비활성화
4. 패널티리스트 상하 정렬이 자꾸 뒤틀려서 이것도 일단 해결은 했으나.. 코드가 좀 맘에 안들어서...... 나중에 리팩토링을 한 번 해야될 것 같습니다..ㅠㅠ
5. api 인스턴스 적용 
<br>
<br>

#411 Fix: 추가 qa 수정 - 다현

---

src/components/Admin/Cardinal.tsx
src/components/Admin/DirectCardinal.tsx
src/components/Admin/DuesRegisterAdd.tsx
src/hooks/admin/handleFileChange.tsx
src/pages/Home.tsx
src/pages/admin/AdminMember.tsx

어드민 회비 파일 확장자 qa 수정했습니다
<br>
<br>
예를 들어서 pdf를 올려보면 이렇게 alert 메시지 나오도록 수정했습니다
- 파일 확장자 제한
- home 화면 최근 기수 보이도록 수정
- 멤버 관리 기수 스크롤 수정
- 패널티 오타 수정
<br>
@yezzan9 머지하기 전에 홈 화면 수정한 부분 봐주세용
<br>

#414 Fix: 어드민 회비 파일 확장자 qa 수정

---

src/pages/Landing.tsx

랜딩 페이지에서 신규 회원 가입 버튼이 호버시 포인터가 변경 되지 않는 문제를 발견하여 수정하였습니다.
<br>
<br>
<br>
<br>
<br>

[hotfix] #422 Landing 페이지 신규회원가입 호버시 포인터 변경 수정

---

src/pages/Landing.tsx

배포 환경과 개발 환경, 로컬 환경에 따른 카카오 로그인 리다이렉트 URI 를 동적으로 할당하였습니다.
<br>
<br>
<br>
<br>
<br>

[hotfix] #424 kakao redirect uri 동적 할당

---

src/pages/Landing.tsx

main으로 병합합니다.
<br>
<br>
<br>
<br>
<br>

Merge release/v2.0.0 to main

---

src/components/Signup/PositionSector.tsx
src/pages/Profile.tsx

신규 파트인 PM을 회원 가입 화면에서 추가하였습니다.
<br>
다른 어드민/홈페이지에서도 PM 파트 추가가 필요합니다.
<br>
<br>
<br>
<br>

[hotfix] #428 PM 파트 추가

---

src/api/api.ts
src/api/deleteComment.tsx
src/api/deletePost.tsx
src/api/patchAttend.tsx
src/api/postComment.tsx
src/api/uploadFiles.tsx
src/api/useGetBoardDetail.tsx
src/api/useGetBoardInfo.tsx

환경변수 동적 할당을 제거합니다.
<br>
<br>
<br>
<br>
<br>

[hotfix] #432 환경변수 동적할당 제거

---

src/pages/Redirect.tsx

로그인 실패시 토스트 메시지가 뜨도록 작성하였습니다.
<br>
<br>
<br>
<br>
<br>

[hotfix] #435 로그인 실패시 토스트 메세지 보여주기

---

package-lock.json
package.json
src/App.css
src/components/Board/Comment.tsx
src/components/Board/PostDetailMain.tsx
src/components/Board/ReplyComment.tsx
src/components/Event/EventContent.tsx
src/components/Event/EventEditor.tsx
src/hooks/convertLinksInText.tsx
src/pages/BoardNoticePost.tsx
src/styles/board/Comment.styled.ts
src/styles/board/PostDetail.styled.ts
src/styles/event/EventContent.styled.ts

#437 을 구현했습니다
<br>
<br>
공지사항의 경우 게시판과 동일한 컴포넌트를 공유하고 있어 같이 변경됩니다!
이렇게 받은 값을
이렇게 보여줍니다~!
<br>
게시판, 공지사항, 일정에 링크 작성 시 하이퍼링크 기능을 추가하였습니다.
문자열이 `https://` 혹은 `www.`로 시작해야하며, 해당 문자열에서 다음 공백이 나오기까지를 하나의 링크로 판단합니다.
<br>
해당 PR approve 해주시면, 이 수정사항을 realese, main에도 병합하겠습니다!
<br>

#437 feat: 하이퍼링크 구현

---

src/api/useGetDuesInfo.tsx
src/pages/Dues.tsx

회비 페이지에서 발생한 무한 로딩을 해결했습니다.. 
기수를 최신순으로 바꾸면서 회비 페이지 접속시 무한 로딩이 발생했습니다,,
마스터 계정의 경우 0기를 기수로 넣어주는데 0기는 오류로 판별하는 로직을 넣어놨어서 문제가 발생했습니다,, 해당 로직 수정하여 문제 해결했습니다!
<br>
- 회비 무한 로딩 해결!~!
해당 pr 머지후 release와 main에도 머지 하겟습니다~!!
그냥 핫픽스 할 걸 그랫네요..

#439 Fix: 회비 오류 수정

---

src/api/useGetDuesInfo.tsx
src/components/Dues/DuesInfo.tsx
src/components/Dues/DuesTitle.tsx
src/components/Receipt/ReceiptMain.tsx
src/pages/Dues.tsx

develop을 release로 머지 합니다!
<br>
<br>
<br>
<br>

Merge develop to release/v2.0.0

---

src/components/Admin/AttendDropdown.tsx
src/components/Event/EventTitle.tsx
src/components/Member/MemberList.tsx
src/components/common/Loading.tsx
src/constants/departmentConstants.ts
src/constants/departmentConstatns.ts
src/pages/BoardNoticeEdit.tsx
src/pages/BoardNoticePost.tsx
src/pages/EventDetail.tsx
src/pages/NoticeDetail.tsx
src/styles/board/Comment.styled.ts

#453 을 구현했습니다.
<br>
<br>
https://github.com/user-attachments/assets/67fa560c-7879-4995-a244-162f06228542
https://github.com/user-attachments/assets/86e38539-c14c-45ea-8fc0-493832d25593
<br>
-  게시글 생성/수정 시 에러 문구 세분화
에러 발생 시 '게시글or공지사항 작성 중 문제가 발생했습니다'라고 뜨도록 하고, 글자수가 너무 많은 경우에는 api요청을 보내지 않도록 했습니다.
-  홈에서 공지 바 접근 → 뒤로가기 눌렀을 때 홈이 아닌 공지리스트로 이동하도록
-  멤버 기수별 조회 시 무한스크롤 안됨
hasNoMember값이 초기화되지 않아서 생기는 이슈였습니다,, 초기화하도록 하여 해결완료했습니다!
-  댓글 옆구리터짐이슈 해결
- 어드민 출석 리스트 렌더링 시 학과 enum → string으로 변경 (ex. SW → 소프트웨어전공)
<br>
textarea 기본 스크롤을 안보이게하고, 해당 부분을 다시 div태그로 감싸서 스타일된 스크롤바를 적용하고 싶은데, 현재 개발환경이 맥이라 확인이 어렵습니다,,🥺 윈도우 사용하시는 분이 수정해주시면 좋을 것 같아요🥺🥺🥺🥺
<br>

#453 fix: 추가 수정사항 반영

---

src/api/useGetMonthSchedule.tsx
src/components/Calendar/MonthCalendar.tsx
src/styles/calendar/MonthCalendar.styled.ts

#415 를 구현했습니다
<br>
기본 스타일링이 있는 이슈가 ... 배경이 어두운 색이라 겹쳐서 여태 몰랏ㅇㅓ요 ..
그치만 해결했습니다..!!
<br>
https://github.com/user-attachments/assets/33453048-cb15-4749-9232-77b89100bc84
<br>
- 캘린더 디자인 변경사항 반영
- 일정 클릭 시에도 날짜가 선택되도록 수정
<br>
막 많이 수정한 건 아니라 한 분만 approve 해주시면 머지하도록 하겠습니다😊
<br>

#415 feat: 캘린더 디자인 수정

---

src/api/postBoardNotice.tsx

게시물 작성 에러를 해결하기 위해 변경
게시판에 게시물 작성 시 파일명에 특수문자가 포함된 경우 에러가 발생했습니다! 
- 파일 업로드 전 파일명 인코딩 처리 추가

#471 Fix: 파일 업로드 에러 해결

---

index.html
src/components/Admin/DirectCardinal.tsx
src/components/Admin/DuesRegisterDropDown.tsx
src/components/Dues/DuesInfo.tsx
src/pages/admin/AdminAttendance.tsx
src/pages/admin/AdminDues.tsx
src/styles/admin/DuesRegisterAdd.styled.ts
src/styles/admin/ExpenditureRecord.styled.ts
src/styles/admin/TotalDues.styled.ts
src/types/adminCardinal.d.ts

#474 를 구현하였습니다.
<br>
<br>
[어드민] 회비 지출 기록 각 기록 하단 여백 설정
<br>
[어드민] 회비 영수증 첨부 컨테이너 간의 정렬 수정
<br>
[어드민] 출석 default 기수 최신 기수로 설정
<br>
[어드민] 총 회비 최초 등록 토글 버튼 svg 변경
<br>
회비 천 단위에 따른 쉼표 추가
<br>
- 회비 천 단위에 따른 쉼표 추가
- [어드민] 회비 영수증 첨부 컨테이너 간의 정렬 수정
- [어드민] 회비 지출 기록 각 기록 하단 여백 설정
- [어드민] 총 회비 최초 등록 토글 버튼 svg 변경
- [어드민] 출석 default 기수 최신 기수로 설정
- [어드민] 총 회비 최초 등록 오타 수정
- RN 마이그레이션 시 적용 안되는 폰트 추가
<br>
*[어드민] 회비 영수증 첨부 컨테이너 간의 정렬 수정* : 해당 부분에서 제 노트북 기준에서는 정렬이 잘 맞아서 확인이 어렵습니다.. 다들 한 번 정렬 확인 부탁 드립니다!
<br>

#474 Refactor: 유저 테스트 수정 반영

---

src/components/Admin/NavMenuList.tsx
src/components/Admin/SearchBar.tsx
src/pages/admin/AdminMember.tsx
src/styles/admin/AdminLayout.styled.ts

#475 를 구현했습니다
<br>
<br>
- 검색바 이중 border 제거 
- 멤버 관리 페이지 Top bar  부연 설명 제거
<br>
- 관리자 매뉴얼 연결 
- 검색바 focus 시 border 제거 
- 멤버 관리 top bar 설명 수정 
<br>
어드민 공통 레이아웃에서 스크롤 시 왼쪽과 오른쪽 여백이 다른 것은 아직 해결하지 못했습니다... 
주석처리된 부분은 이것저것 수정해보다가 해결하지 못한.. 흔적입니다.. 
언젠가 꼭 다음 이슈에서 해결해볼게요.. 
<br>

#475 Fix : 임원진 qa  반영

---

src/components/Board/ContentPost.tsx
src/components/Board/PartBoard.tsx
src/components/Event/EventEditor.tsx
src/components/Event/EventTitle.tsx
src/components/Header/Header.tsx
src/components/common/MenuModal.tsx
src/pages/MyPage.tsx
src/pages/board/education/EducationBoard.tsx
src/pages/board/notices/BoardNotice.tsx
src/styles/board/Board.styled.ts
src/styles/board/Markdown.styled.ts
src/styles/board/PostDetail.styled.ts

#500 를 구현하였습니다.
<br>
<br>
<br>
- 글쓰기_파일 리스트 가로 스크롤 되도록 수정
- 파트게시판에서 전체 없애기
- 교육자료 및 공지사항 헤더 어드민 아닌 경우 수정
- 캘린더 일정 수정 페이지에서 드롭다운 관련 수정
- 일정 추가 페이지 헤더 column 되도록 수정
- PC뷰 일경우 content 박스 height 수정
- 게시판 공지사항 스크롤 패딩 적용
- 교육자료 카드 호버 색상 추가
- 체크리스트 구현 시 동그라미 marker 안나오도록 수정
<br>
<br>

#500 Refactor: 2차 qa사항 반영
