src/App.js
src/pages/Login.jsx
src/pages/Signin.jsx

Weeth 초기 화면 페이지의 css 작업 완료
회원가입 버튼을 누를 시 signup 페이지(회원가입 페이지)
로그인 버튼을 누를 시 signin 페이지(로그인 페이지)
로 이동할 수 있게 하였다.
- 이상하게 npm start로 처음에 들어가면 규격이 안 맞을 때도 있었다..

#47 design: 초기화면 UI 구현

---

src/components/Attendance/AttendCheckMain.jsx
src/components/Caption.jsx
src/components/home/HomeMain.jsx

출석 조회 페이지 css 설정
attend라는 bool 타입의 변수를 props로 받아와 출석인지 결석인지 조건부로 렌더링
출석 List에 필요할 거 같은 data
```
attend: PropTypes.bool.isRequired,
title: PropTypes.string.isRequired,
week: PropTypes.string.isRequired,
date: PropTypes.string.isRequired,
place: PropTypes.string.isRequired,
```
중간 중간 커밋해야지 되는데 귀찮아서 작업 다 하고 커밋 한 번으로 퉁친다..
담부터는 고치도록 하겟습니다..
+아 그리고 홈에 그리드 아이템 커서 효과가 없어져서 추가햇어요

#57 design: 출석 조회 페이지 css 설정

---

src/components/Attendance/AttendHeader.jsx
src/components/BoardTitle.jsx
src/components/Calendar/CalendarHeader.jsx
src/components/Header/Header.jsx
src/components/Header/LeftButton.jsx
src/components/Member/MemberHeader.jsx
src/components/MyPage/MyPageHeader.jsx

뒤로가기 기능 추가
- LeftButton이 모든 페이지에서 동일하게 뒤로가기로 사용되어 props를 제거하고 컴포넌트 자체에 기능을 추가하였음
출석 페이지에는 뒤로가기가 `window.history.back();`로 구현되어 있었는데, 리액트 앱 구조에서는 `useNavigate(-1)`를 이용하는 것이 권장된다고 함.
그래서 useNavigate를 이용했습니다~

[feat] 뒤로가기 추가

---

.eslintignore
src/App.js
src/components/Board/NoticeHeader.jsx
src/pages/Board.jsx
src/pages/BoardNotice.jsx

게시판 글 페이지에서 구현하지 못했던 세부 기능 개발
-리액트에서 기본 메뉴 창을 가져오기 어려워서 최대한 비슷하게 만들어봤습니다
- 이전 이슈에서 board 페이지 안 보였던 문제 해결
- 클릭 시 색 변하게 하는 건 다음 이슈 때 구현

#95 feat: 게시판 상세 기능 구현

---

src/components/Attendance/AttendMain.jsx

users api에서 이름 가져올 때 에러나면 출석 페이지 전체 컴포넌트가 안 보였는데 이름에 해당하는 부분에만 에러처리 되도록 수정

#97 fix: 출석 이름 가져올 때 에러 로직 수정

---

src/components/Member/Category.jsx
src/components/Member/InfoComponent.jsx
src/hooks/UserAPI.jsx
src/hooks/UserContext.js
src/pages/Edit.jsx
src/pages/Member.jsx
src/pages/MyPage.jsx

멤버 api 연결
- 마이페이지 / 개인정보 수정 / 동아리원 조회 연결 완료
- 개인정보 수정 페이지의 경우 기존의 값을 가져오기만 하고, 수정하는 부분은 구현되지 않음
-  에러 시 해당 컴포넌트에 대해서만 에러가 뜨도록 수정했습니당
- 일단 캘린더 GET 연결 다 끝내고 멤버 PATCH(개인정보 수정) / DELETE(탈퇴) 마저 하겠습니당
- 현재 1기/2기 유저 데이터가 없어서 누르면 에러가 뜹니다 ㅜ-ㅜ 데이터가 없는 경우 다른 에러메세지를 나타나게 하는 게 나을지 고민 중....

#77 feat: member api 연결

---

src/App.js
src/components/Receipt/ReceiptMain.jsx
src/hooks/DuesContext.js
src/pages/Dues.jsx
src/pages/Receipt.jsx

회비 api 연결
영수증 사진 누를시 모달창으로 뜨게 변경(디자인팀 컨펌 완료)
수입 지출 구분 가능한 data 하나 넣어달라구 말씀 드렸음 단톡에서 말 나온 것처럼 수입이 많지 않은데 굳이 구분이 필요한가에 대해 논의가 필요한 것 같아 정해지면 나중에 수정할 듯
App.js에서 헤원이가 수정한 부분이랑 내가 수정한 부분이 충돌나서 그거 해결하고 로그인  페이지 중복 import 해결 했습니다~

#124 feat: 회비 api 연결

---

.eslintignore
src/hooks/Utils.js
src/pages/Login.jsx

로그인 페이지 API 연결 및 기능 구현하기
로그인 페이지에서 이메일 입력 시 상황에 따른 에러 메시지 뜨게 하기 / 로그인 허용되도록 구현하기
- 이메일 불일치 문제
- 비밀번호 불일치 문제
- Utils.js의 기능:  페이지에서 토큰이 만료되었을 때, 토큰 재발급을 위한 용도
-Utils.js 사용 방법 :  Utils 함수를 호출해서 매개변수를 넣고, 저장한 변수를 사용하기 
-매개변수
1. response: 응답객체
2. originalApiFunc : 원래 호출된 API 함수
3. originalParams: 원래 API 호출 시 사용된 매개변수들
4. navigate: 다른 페이지로 리디렉션할 때 사용
-Utils.js 사용에 대한 상세한 적용 방법은 Login.jsx에서 확인하실 수 있습니다!(주석도 참고하기)
-원래는 case가 가입된 이메일이 아닌 경우까지 총 3가지인데 회원가입 API를 완료하지 못해서 아직은 안 보입니다!

#127 feat: 로그인 페이지 API 연결 /기능 구현하기(최종)

---

src/components/BoardTitle.jsx
src/pages/EditEvent.jsx
src/pages/EventDetails.jsx

일정 수정 api 연결
1. /event/{eventId} 가져오는 api 수정.. 
- 원래 일정 상세페이지가.. 캘린더에서 받아온 기간 일정 중 해당하는 id의 값을 함께 넘겨주면서 렌더링하는거라 새로고침하면 값이 사라졋는데, 상세페이지에서 api를 받아오도록 수정해서 새로고침 가능합니다^_^~
- 추후 리팩토링이 필요할 것 같음. context로 가져오려햇으나 어떻게 해도 안되더라구요.. 이러다가 완성을 못할 것 같아서 그냥 냅다 연결햇습니다
2. 수정 api도 구현 완료!
이게 api 연결은 금방 햇는데 원래 데이터를 가져와서 보여주는 게 잘 안돼서 오래걸렷네요... ^_ㅠ

#143 feat: 일정 수정 api

---

src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/YearCalendar.jsx
src/hooks/Utils.js
src/pages/Calendar.jsx
src/pages/CreateEvent.jsx
src/pages/EventDetails.jsx

일정 관련 수정
**✔️ 일정 상세페이지에서 내용에 줄바꿈처리**
- css 설정 추가하여 \n을 줄바꿈으로 보이도록
- 수정페이지가 자꾸 문제가 많아서 .. 생성-수정이 같은 컴포넌트를 공유하도록 리팩토링해서 해결할 예정! axios함수랑 input 초기필드만 달라서 공유하는 편이 효율적일듯.
**✔️ 현재달 표시 수정**
- 원래는 month 변수를 이용하여 확인했는데, month가 state값이라서... 캘린더(달)에서 달을 변경하면 현재달 표시도 꼬이는 이슈
- Date객체를 새로 만들어서 비교하는 방법으로 해결
- 해결하면서 현재 년도가 아닌 경우에는 현재달이 표시되지 않도록 수정함 (2023년으로 넘길 경우 2023년 8월에도 현재달 표시가 됐었는데, 2024년 8월인 경우에만 표시되도록 함)
**✔️ 달력에 표시되는 일정 제목은 일단 css로 말줄임표 처리함**
남은 수정 이슈들이 거의 css거나 모든 페이지에 공통으로 사용되는 부분이라 (+해결이 잘 안돼서,,) 리팩토링 먼저 진행하겟습니당,,,,

#172 feat: 일정 관련 수정

---

.eslintignore
src/App.js
src/components/BoardTitle.jsx
src/components/Calendar/MonthCalendar.jsx
src/components/Calendar/MonthlyEvent.jsx
src/components/Calendar/YearCalendar.jsx
src/hooks/EventInfoAPI.jsx
src/hooks/YearlyScheduleAPI.jsx
src/hooks/YearlyScheduleContext.js
src/pages/CreateEvent.jsx
src/pages/EventDetails.jsx

서버 수정에 따른 api url 및 dto 수정
- api 및 dto 수정
- isMeeting값에 따라 각각 다른 api를 불러오도록 수정
- event를 조회하면 event와 meeting의 값이 전부 반환되는데, event와 meeting끼리는 id가 겹쳐서 캘린더에서 꼬이는 이슈가 있었음
- 우선은 상세 페이지 api연결을 위해 프론트에서 중복 id를 처리했지만 이 부분을 프론트/백 중 어디에서 처리하는 게 좋을지, 혹은 다른 방법이 없을지는 조금 더 고민을 해봐야할듯함!
- 리팩토링 후 일정 수정이 사용될 수 있도록 하려 했으나,,, 해당 이슈가 너무 길어질 것 같아서 리팩토링은 새 이슈를 만들어서 해결하도록 하겠습니당 !! 현재는 일정 수정이 제대로 되지 않는 게 맞습니다... !!
- App.js에서 충돌이 났는데 해당부분 롤백했다고 해서 기존 파일을 남겨두는 방향으로 충돌 해결햇습니다,,

#177 fix: api 수정

---

src/components/Calendar/MonthCalendar.jsx
src/components/DropdownMenu.jsx
src/components/Member/Category.jsx
src/components/MyPage/InfoInput.jsx
src/pages/AttendCheck.jsx
src/pages/Attendance.jsx
src/pages/Calendar.jsx
src/pages/Dues.jsx
src/pages/Edit.jsx
src/pages/EventAdmin.jsx
src/pages/EventDetails.jsx
src/pages/Home.jsx
src/pages/Landing.jsx
src/pages/Login.jsx
src/pages/Member.jsx
src/pages/MemberDetail.jsx
src/pages/MyPage.jsx
src/pages/Profile.jsx
src/pages/Receipt.jsx
src/pages/Signup.jsx
src/router/useCustomBack.jsx

많은 것들을 수정..~
- api 도메인 수정
- 드롭다운 수정
- 이름 입력제한 - 한글 5글자 이내
- textarea에서는 스크롤바 마진을 설정할 수 없어서,, div태그를 하나 더 감싸서 영역 조절 후 여백 구현했습니당
원래 문제점 : 수정 페이지의 경우 뒤로가기 시 홈이 아닌 수정페이지로 돌아가는 이슈,,
브라우저 히스토리는 방문한 대로 저장이 되니까,,, 홈 > 마이페이지 > 수정 > 마이페이지 이런식으로 저장이 돼서 수정 후 뒤로가기를 하면? 당연히 직전 페이지인 수정으로 넘어가겠죠! 이러면 안되는데!...ㅜㅜ
하여튼 뒤로가기에 이런 문제가 있었는데요,, 원래 그냥 navigate하는 hook을 사용하려했지만,, `브라우저 자체의 뒤로가기를 사용하는 경우는 어떻게 제한함?` 이라는 큰 이슈가,,,,
있었지만,,,,
`useCustomBack`을 이용하여 브라우저 뒤로가기를 제어할 수 있게 됐습니다,,,
뒤로가기 사용시 원하는 경로로 리다이렉트를 하는 hook이에요 ^___^
각각의 페이지에서 import 후 매개변수로 원하는 경로를 입력해주면 댑니다,,
- 온클릭함수로 설정이 안 되어있어서 추가했습니다..~
뒤로가기를 모든 페이지에 설정했는데 게시판은 confilct 날 것 같아서 일단 냅뒀어용,,

#196 fix: 멤버 카테고리 및 뒤로가기 수정

---

src/App.js
src/components/Attendance/AttendCheckMain.jsx
src/components/Attendance/AttendMain.jsx
src/components/home/HomeMain.jsx
src/hooks/DuesAPI.jsx
src/hooks/UserAPI.jsx
src/hooks/Utils.js
src/pages/Home.jsx
src/pages/Login.jsx

서버를 열심히 괴롭히며.. 하루를 쏟아부어,, 토큰 유효성 검사 거의? 완료 했습니당
**1. 액세스 토큰 유효/ 리프레시 토큰 유효**
서버: status 200, body에 data 담아줌
프론트: Utils.js에서 body data 있나 확인 후 있으면 걍 사용 
**2. 액세스 토큰 만료/ 리프레시 토큰 유효**
서버: status 200, body 비어있음
프론트: Utils.js에서 body가 비어있으면 새로 토큰을 저장하고 해당 api를 재 실행함
**3. 액세스 토큰 만료/ 리프레시 토큰 만료**
서버: status 403
프론트: 이 때는 Utils.js 실행하지 않고 api componenet(예시: UserAPI)에서 에러를 catch 하여  로그인 페이지로 리다이렉션 함
현재 api component에서 catch 구문에 로그인 리다이렉션 구현한 건 UserAPI와 DuesAPI입니다. UserAPI를 사용하지 않는 페이지가 있다면 알려주세요! 해당 페이지에서 사용하는 api에 로그인 리다이렉션 추가가 필요합니다. 
++ 현재 액세스 토큰 유효기간 5분 리프레시는 3분이라 로그인 하고 3분 지나면 로그인 페이지로 리다이렉션 됩니다ㅎ.ㅎ

#216 fix: util 수정

---

src/hooks/DuesAPI.jsx
src/hooks/DuesContext.js
src/pages/Dues.jsx

어드민 페이지에서 입력한 회비 설명이 유저에게도 보여지도록 수정했습니다

[fix] 회비 사용내역:  운영진이 입력한 내용이 뜨도록 수정

---

src/components/Calendar/CalendarHeader.tsx
src/components/Calendar/DateInput.tsx
src/components/Calendar/DatePicker.tsx
src/components/Calendar/EventDetailTitle.tsx
src/components/Calendar/ModalMonthContent.tsx
src/components/Calendar/MonthCalendar.tsx
src/components/Calendar/MonthlyEvent.tsx
src/components/Calendar/ToggleButton.tsx
src/components/Calendar/YearCalendar.tsx
src/components/Member/Category.tsx
src/components/Member/InfoComponent.tsx
src/components/Member/MemberHeader.tsx
src/components/Member/MemberName.tsx
src/components/MyPage/InfoInput.tsx
src/components/MyPage/MyPageHeader.tsx
src/styles/calendar/CalendarHeader.styled.ts
src/styles/calendar/DateInput.styled.ts
src/styles/calendar/DatePicker.styled.ts
src/styles/calendar/EventDetailTitle.styled.ts
src/styles/calendar/ModalMonthContent.styled.ts
src/styles/calendar/MonthCalendar.styled.ts
src/styles/calendar/MonthlyEvent.styled.ts
src/styles/calendar/ToggleButton.styled.ts
src/styles/calendar/YearCalendar.styled.ts
src/styles/memeber/Category.styled.ts
src/styles/memeber/InfoComponent.styled.ts
src/styles/memeber/MemberName.styled.ts
src/styles/mypage/InfoInput.styled.ts

코드 가독성을 위하여 styled-component를 분리하였습니다
<br>
<br>
<br>
- 캘린더, 멤버, 마이페이지에 대해 styled-component를 분리하였습니다
- Header 폴더의 경우 프로젝트 내에서 사용되는 모든 헤더를 하나로 통합할 예정 -> 통합하면서 수정하는 편이 나을 것 같아 수정하지 않았습니다!
- 각 페이지 폴더 내에 있는 헤더 컴포넌트도 위와 동일한 이유로 분리하지 않았습니다
- component 폴더내에 하위폴더 없이 존재하는 컴포넌트들은 폴더구조 어떻게 할지 회의 먼저 하고 분리합시다,,<br><img width="177" alt="스크린샷 2024-10-19 오전 1 21 26" src="https://github.com/user-attachments/assets/56fb5fd7-fcbe-4944-8923-115fd0fa9a04">
<br>
import 정렬이 하나도 안 되어 있어서 제 vsc에 자동 정렬되는 설정을 추가했습니다
노션 FE 필독에 추가해두었으니 확인하고 같이 설정해두면 좋을 것 같아요!!
<br>

#247 refactor: styled component 분리 (캘린더, 멤버, 마이페이지)

---

src/components/Admin/AttendDropdown.tsx
src/components/Admin/Attendance.tsx
src/components/Admin/Cardinal.tsx
src/components/Admin/NavMenu.tsx
src/pages/admin/AdminAttendance.tsx

어드민 출석 관리 UI 구현
<br>
없습니다. 
<br>
<br>
- 전반적인 UI 구현 완료 (기수는 추후 수정, 출석 dropdown -> 새이슈로 만들 예정)
<br>
원래 위드 페이지 색상이 전체 검정색으로 구현되어있는데, 어드민 페이지는 흰색으로 구현을 해야해서 현재 일단은 100vw, 100vh로 설정해두었습니다. 
현재 어드민 출석 관리 UI 구현 중인데 공통 부분에서 충돌날것 같아서 먼저 pr 올리고 출석 dropdown 부분과 기수는 새로운 이슈파서 다시 수정할 예정입니다.
<br>

#297 feat: 어드민 출석 관리 UI 구현

---

src/App.jsx
src/api/useGetDuesInfo.tsx
src/api/useGetGlobaluserInfo.tsx
src/components/Dues/DuesTitle.tsx
src/components/Event/EventEditor.tsx
src/components/Receipt/ReceiptMain.tsx
src/components/common/AdminOnly.tsx
src/components/home/HomeMain.tsx
src/hooks/useGetUserName.tsx
src/pages/Dues.tsx
src/pages/EventDetail.tsx
src/pages/EventPost.tsx
src/pages/admin/AdminAttendance.tsx
src/pages/admin/AdminDues.tsx
src/pages/admin/AdminMember.tsx
src/pages/admin/AdminPenalty.tsx

#281 을 구현했습니다
<br>
api 인스턴스를 적용 못 했는데 ... 어차피 추가로 수정작업 해야하는 api들이 있어서 한번에 하도록 하겠습니다! 그 외 부분만 봐주세요,,
<br>
<br>
마이페이지가 아닌 곳에서 내 정보를 조회해야할 때는 아래 코드를 사용해주시면 됩니다!
```
const { globalInfo } = useGetGlobaluserInfo();
```
그리고 `useGetGlobaluserInfo()`의 return 값으로 `isAdmin`도 있으니, 어드민인지 확인이 필요한 경우에는 이렇게 바로 사용 가능합니다!
```
const { isAdmin } = useGetGlobaluserInfo();
```
기존에 `userInfo`로 사용되고 있던 부분을 `globalInfo`로 수정하였으니, 확인 부탁드립니다.
이렇게 수정하면서 globalInfo를 받아온 후에 회비 조회 요청을 보낼 수 있도록 기수가 default값(0)이면 api 요청을 보내지 않도록 설정했습니다.
이게 원래는 라우팅단계에서 막으려고 했으나,,, 안되는 이유를 찾지 못해 우선은 컴포넌트를 렌더링하는 방식으로 구현했습니다. 추후 리팩토링을 고려하고 있습니다
디자인은 임의로 설정해둔 것이며, 수정될 수 있습니다
어드민이 아닐 경우 접근을 제한해야하는 페이지에서 `<AdminOnly />` 컴포넌트를 추가해주면 됩니다! 모든 로직은 해당 컴포넌트 내에 있어서 따로 추가할 내용은 없습니다🤩
다만, 디자인 통일성을 위해 조건을 설정해두었습니다.
서비스 단에서 접근을 막아야할 경우에는 props 값을 전달하지 않아도 …

#281 feat: 어드민 체크 분리

---

src/App.jsx
src/api/getEventInfo.tsx
src/api/useGetAllUsers.tsx
src/components/Event/EventTitle.tsx
src/components/Member/MemberList.tsx
src/components/common/CardinalDropdown.tsx
src/components/common/MenuModal.tsx
src/pages/BoardPostDetail.tsx
src/pages/Member.tsx
src/pages/MyPage.tsx
src/pages/NoticePostDetail.tsx

#381 을 구현했습니다
<br>
기수 드롭다운이 height 제한이 없어 너무 길어져서,,, 우선 피그마에 남겨둔 상태입니다 ! 
<br>
<br>
- 메뉴모달 위치 수정
드디어 이 녀석을 해결했습니다,, Container 내부에 스타일드 컴포넌트를 하나 더 추가하여 `width: 370;` 설정을 추가하여 뒷배경은 전체를 유지한 채 모달만 370px 내에 위치하도록 했습니다! 이제 모든 페이지에서 같은 위치에 나타납니다....(´༎ຶོρ༎ຶོ`)
- 멤버 검색 시 마지막 멤버입니다. 뜨지 않도록
- 멤버 검색 시 엔터로 검색
- 멤버 기수별 조회 안되는 오류 수정
- 기수 드롭다운 내림차순으로 수정
<br>
<br>

#381 fix: 멤버 qa 수정

---

src/api/admin/cardinal/postCardinal.ts
src/api/useGetCardinals.tsx
src/components/Admin/Box.tsx
src/components/Admin/ButtonGroup.tsx
src/components/Admin/CardinalInfo.tsx
src/components/Admin/CardinalSearchBar.tsx
src/components/Admin/DirectCardinal.tsx
src/components/Admin/Modal/CardinalEditModal.tsx
src/components/Admin/Modal/CardinalModal.tsx
src/components/Admin/Modal/CommonCardinalModal.tsx
src/components/Admin/Modal/MemberDetailModal.tsx
src/components/Admin/NavMenuList.tsx
src/components/Admin/PenaltyListTable.tsx
src/components/Admin/SearchBar.tsx
src/components/Admin/SortButton.tsx
src/components/Admin/context/MemberContext.tsx
src/pages/admin/AdminPenalty.tsx
src/styles/admin/cardinal/CardinalInfo.styled.ts
src/styles/admin/cardinal/CardinalModal.styled.ts
src/utils/admin/getHighestCardinal.ts
src/utils/admin/handleNumericInput.ts

#377 를 구현하였습니다.
<br>
기수 수정할 때 이미 저장된 연도 및 학기일 경우를 수정이 안되도록 하는게 좋지 않을까 싶은데.. 배겐드에게 물어봐야 할듯.. 
그래서 현재 8기,9기가 모두 2026년 2학기라는 점.. 
-> 회의 때 말한대로 그정돈 유저의 책임으로 전가하도록 
<br>
나머지는 자잘한거라.... 이정도만 첨부하겠습니다
<br>
구현하지 못한 기수 관련된 수정사항들을 모두 구현했습니다 .............. 
<br>
이제 남은 건 qa 수정.. 신난다 ! 
<br>

#377 Refactor: 기수 관련 UI 수정 및 추가 api 연결

---

src/api/api.ts
src/api/deleteComment.tsx
src/api/deletePost.tsx
src/api/patchAttend.tsx
src/api/postComment.tsx
src/api/uploadFiles.tsx
src/api/useGetBoardDetail.tsx
src/api/useGetBoardInfo.tsx
src/pages/Landing.tsx
src/pages/Signup.tsx

BASE_URL을 배포 환경에 따라 동적할당 할 수 있도록 코드를 수정하였습니다.
<br>
window.location.hostname이 서비스 배포 환경인 weeth.site가 아닌 경우,
즉, 개발 배포 환경 또는 로컬 환경에서는 개발 서버로 보내게 수정하였습니다.
<br>
<br>
<br>
<br>

[hotfix] #426 BASE_URL 배포 환경 따라 동적 할당

---

src/components/Header/AdminButton.tsx
src/components/Header/Header.tsx
src/pages/attend/Attendance.tsx

출석 페이지에서 어드민일 경우 어드민 페이지로 바로 이동할 수 있는 컴포넌트를 추가하였습니다.
<br>
<br>
<br>
- `Header` 컴포넌트에서 어드민일 경우 type을 추가하여 분리해두었습니다.
<br>
<br>

WTH-9-WEETH: 출석 어드민 헤더 관리자 페이지 추가

---

package-lock.json
src/components/Board/PartBoard.tsx
src/components/Board/StudyBoardSearch.tsx
src/components/Header/Header.tsx
src/components/home/HomeFooter.tsx

- 릴리즈 후 QA사항을 반영하였습니다.
<br>
<br>
<br>
- 검색 툴 바 모바일에서 깨지는 UI 수정
- 검색 툴바 입력시 좌측만 클릭이 되고 가운데부터 우측은 클릭 안되는 문제 해결
- 헤더 3등분 후 정렬되도록 수정 (전에는 오른쪽 컴포넌트의 크기에 따라 `justify-between`으로 인해 중간 단어 정렬이 안됐었음)
- 파트게시판 `img`태그로 불러와서 화질이 깨졌던 것 같아서 `svg?react`로 컴포넌트로 불러오는 식으로 수정해두었습니다.
<br>
<br>

WTH-16-WEETH: 릴리즈 후 qa 사항 반영

---

src/components/Attendance/AttendMain.tsx
src/components/Penalty/PenaltyItem.tsx
src/styles/penalty/PenaltyItem.styled.ts

- 경고만 있을 때 페널티 상세 페이지 진입 버튼이 뜨지 않았습니다.
- 경고 2회시 부여되는 페널티가 경고 뱃지로 떴습니다.
해당 버그를 해결하기 위해 코드 변경을 했습니다!
- 기존 페널티 존재 여부 확인 코드에 경고 카운트를 추가하여 경고를 받을 시에도 페널티 진입 버튼이 보이도록 했습니다!
- 스타일링 분기 처리를 경고 기준으로 둬서 자동 페널티와 페널티는 페널티 스타일링으로 뜨도록 변경했습니다!
위에 언급한 문제 해결 완료 햇습니다~!!
<br>

WTH-13-WEETH : 페널티 UI 수정
